name: Build/release desktop app

on:
  push:
    tags:
      - v*.*.*

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: build-linux
        if: matrix.os == 'ubuntu-latest'
        run: npm run build:linux

      - name: install-extra-deps
        if: matrix.os == 'macos-latest'
        run: npm install @rollup/rollup-darwin-arm64
      - name: install-extra-deps
        if: matrix.os == 'macos-latest'
        run: npm install dmg-license
      - name: build-mac
        if: matrix.os == 'macos-latest'
        run: npm run build:mac
      - name: build-win
        if: matrix.os == 'windows-latest'
        run: npm run build:win

      - name: list-all-dist-files-windows
        if: matrix.os == 'windows-latest'
        run: dir dist

      - name: list-all-dist-files-mac
        if: matrix.os == 'macos-latest'
        run: ls dist

      - name: list-all-dist-files-linux
        if: matrix.os == 'ubuntu-latest'
        run: ls dist

      - name: Extract version from package.json
        id: extract_version
        run: echo "VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_ENV
        shell: bash

      - name: Create latest.json
        run: |
          echo "{\"version\": \"${{ env.VERSION }}\"}" > latest.json
        shell: bash

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.R2_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          aws-region: auto
          endpoint-url: ${{ secrets.R2_ENDPOINT }}

      - name: Upload build artifacts to R2
        run: |
          # Upload only the installation files
          if [ "${{ matrix.os }}" == "windows-latest" ]; then
            aws s3 cp dist/ s3://${{ secrets.R2_BUCKET }}/releases/${{ env.VERSION }}/ --recursive --exclude "*" --include "*.exe"
          elif [ "${{ matrix.os }}" == "macos-latest" ]; then
            aws s3 cp dist/ s3://${{ secrets.R2_BUCKET }}/releases/${{ env.VERSION }}/ --recursive --exclude "*" --include "*.dmg"
          elif [ "${{ matrix.os }}" == "ubuntu-latest" ]; then
            aws s3 cp dist/ s3://${{ secrets.R2_BUCKET }}/releases/${{ env.VERSION }}/ --recursive --exclude "*" --include "*.AppImage" --include "*.deb"
          fi
        shell: bash

      - name: Upload latest.json to R2
        run: |
          aws s3 cp latest.json s3://${{ secrets.R2_BUCKET }}/latest.json
        shell: bash